/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自動依據 arcfra-wiki/ 目錄的檔案與資料夾結構生成左側導覽樹,
  // 這正對應你截圖裡「文件導覽」這個左側欄——
  // 之後從 Notion 同步進來的資料夾會自動出現在這裡,不需要手動維護。
  kbSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
