/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自动依据 docs/ 目录的文件与文件夹结构生成左侧导航树,
  // 这正对应你截图里「文档导航」这个左侧栏——
  // 之后从 Notion 同步进来的文件夹会自动出现在这里,不需要手动维护。
  kbSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
